# Generated by Django 5.0.6 on 2024-07-11 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('says_who', '0002_life'),
    ]

    operations = [
        migrations.AlterField(
            model_name='life',
            name='life',
            field=models.IntegerField(default=3, max_length=2),
        ),
    ]
