# Generated by Django 5.0.6 on 2024-07-12 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('says_who', '0003_alter_life_life'),
    ]

    operations = [
        migrations.AddField(
            model_name='life',
            name='points',
            field=models.IntegerField(default=0, max_length=3),
        ),
    ]
